Christmas Homework/Music_Rapp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: redirect('/bands')

  resource :session, only: [:new, :create, :destroy]

  resources :users, only: [:show, :new, :create]
  
  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:show, :create, :edit, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:show, :create, :edit, :update, :destroy,]


end

Christmas Homework/Music_Rapp/app/models/album.rb
class Album < ApplicationRecord

    validates :name, :year, presence: true
    validates :live, inclusion: [true, false] 
    validates :name, uniqueness: { scope: :band_id }
    validates :year, numericality: { minimum: 1900, maximum: 9000 }

    after_initialize :set_defaults

    belongs_to :band,
        foreign_key: :band_id,
        class_name: :Band

    has_many :tracks, dependent: :destroy,
        foreign_key: :album_id,
        class_name: :Album


    def set_defaults
        self.live ||= false
    end

end

# == Schema Information
#
# Table name: albums
#
#  id         :integer(8)      not null, primary key
#  name       :string          not null
#  band_id    :integer(4)      not null
#  year       :integer(4)      not null
#  live       :boolean         default("false"), not null
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

Christmas Homework/Music_Rapp/app/controllers/album_controller.rb
class AlbumController < ApplicationController
    before_action :require_user!
  
    def show
        @album = Album.find(params[:id])
        render :show
    end

    def new
        @band = Band.find(params[:band_id])
        @album = Album.new(band_id: params[:band_id])
        render :new
    end

    def create
        @album = Album.new(album_params)
        if @album.save
            redirect_to album_url(@album)
        else
            @band = @album.band
            flash.now[:errors] = @album.errors.full_messages
            render :new
        end
    end

    def edit
        @album = Album.find(params[:id])
        render :edit
    end

    def update
        @album = Album.find(params[:id])

        if @album.update(album_params)
            redirect_to album_url(@album)
        else
            flash.now[:errors] = @album.errors.full_messages
            render :edit
        end
    end

    def destroy
        @album = Album.find(params[:id])
        @album.destroy
        redirect_to band_url(@album.band_id)
    end
    
    def album_params
        params.require(:album).permit(:band_id, :live, :name, :year)
    end
end

Christmas Homework/Music_Rapp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    before_action :require_user!
  
    def show
        @album = Album.find(params[:id])
        render :show
    end

    def new
        @band = Band.find(params[:band_id])
        @album = Album.new(band_id: params[:band_id])
        render :new
    end

    def create
        @album = Album.new(album_params)
        if @album.save
            redirect_to album_url(@album)
        else
            @band = @album.band
            flash.now[:errors] = @album.errors.full_messages
            render :new
        end
    end

    def edit
        @album = Album.find(params[:id])
        render :edit
    end

    def update
        @album = Album.find(params[:id])

        if @album.update(album_params)
            redirect_to album_url(@album)
        else
            flash.now[:errors] = @album.errors.full_messages
            render :edit
        end
    end

    def destroy
        @album = Album.find(params[:id])
        @album.destroy
        redirect_to band_url(@album.band_id)
    end
    
    def album_params
        params.require(:album).permit(:band_id, :live, :name, :year)
    end
end

Christmas Homework/Music_Rapp/app/helpers/album_helper.rb
module AlbumHelper
end

Christmas Homework/Music_Rapp/app/views/albums/_form.html.erb
<% action_url = album.persisted? ? album_url(album) : albums_url %>
<% http_method = album.persisted? ? "PATCH" : "POST" %>
<% button_text = album.persisted? ? "Update Album!" : "Create Album!" %>

<form action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= http_method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <p>
    <label for='album-name'>Name</label>
    <input id='album-name' type="text" name="album[name]" value="<%= album.name %>">
  </p>

  <p>
    <label for='album-band'>Band</label>
    <select id='album-band' name="album[band_id]">
        <% Band.all.each do |band| %>
            <option
                <%= "selected" if album.band_id == band.id %>
                value="<%= band.id %>">
                <%= band.name %>
            </option>
        <% end %>
    </select>
  </p>

  <p>
    <label for="album_studio_t">Studio</label>
    <input
      type="radio"
      name="album[studio]"
      value="t"
      id="album_studio_t"
      <%= "checked" if album.live %>>
    <label for="album_studio_f">Live</label>
    <input
      type="radio"
      name="album[studio]"
      value="f"
      id="album_studio_f"
      <%= "checked" if !album.live %>>
  </p>

  <p>
    <label for='album-year'>Year</label>
    <input id='album-year' type="number" name="album[year]" value="<%= album.year %>">
  </p>

  <input type="submit" value="<%= button_text %>">
</form>

Christmas Homework/Music_Rapp/app/views/albums/edit.html.erb
<h1>Edit <%= @album.name %></h1>

<%= render "form", album: @album %>

Christmas Homework/Music_Rapp/app/views/albums/new.html.erb
<h1>New <%= @band.name %> Album</h1>

<%= render "form", album: @album %>

Christmas Homework/Music_Rapp/app/views/albums/show.html.erb
<h1><%= @album.name %></h1>

<% if @album.tracks.length > 0 %>
  <ul>
    <% @album.tracks.each do |track| %>
      <li><a href="<%= track_url(track) %>"><p><%= track.name %></p></a></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no tracks in this album!</p> 
<% end %>

<h4Links</h4>
<ul class='links'>
  <li><a class='button' href="<%= new_album_track_url(@album) %>">New track</a></li>
  <li><a class='button' href="<%= edit_album_url(@album) %>">Edit album</a></li>
  <li>
    <form action="<%= album_url(@album) %>" method="POST">
      <input type="hidden" name="_method" value="DELETE">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
      <input type="submit" value="Destroy Album">
    </form>
  </li>
  <li><a class='button' href="<%= band_url(@album.band) %>">Back to <%= @album.band.name %></a></li>
</ul>