Christmas Homework/Reddit_Clone/config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: redirect('/subs')

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :comments, only: [:create, :show] 
  resources :subs, except: [:destroy]
  resources :posts, except: [:destroy, :index] 

end

Christmas Homework/Reddit_Clone/app/models/sub.rb
class Sub < ApplicationRecord

    validates :description, :name, presence: true
    validates :name, uniqueness: true

    has_many :post_subs, inverse_of: :sub, dependent: :destroy

    has_many :posts, through: :post_subs, source: :post

    belongs_to :owner,
        class_name: :User,
        foreign_key: :owner_id,
        inverse_of: :subs

end

# == Schema Information
#
# Table name: subs
#
#  id          :integer(8)      not null, primary key
#  owner_id    :integer(4)      not null
#  name        :string          not null
#  description :text
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

Christmas Homework/Reddit_Clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
    before_action :require_signed_in!, except: [:index, :show]
    before_action :require_user_owns_sub!, only: [:edit, :update]

    def index
        @subs = Sub.all
        render :index
    end

    def new
        @sub = Sub.new
    end

    def show
        @sub = Sub.find(params[:id])
    end

    def create
        @sub = current_user.subs.new(sub_params)
        if @sub.save
            redirect_to sub_url(@sub)
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :new
        end
    end

    def update
        @sub = Sub.find(params[:id])
        if @sub.update(sub_params)
            redirect_to @sub
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :edit
        end
    end

    def edit
        @sub = Sub.find(params[:id])
    end

    def sub_params
        params.require(:sub).permit(:name, :description)
    end
end

Christmas Homework/Reddit_Clone/app/helpers/subs_helper.rb
module SubsHelper
end

Christmas Homework/Reddit_Clone/app/views/subs/_form.html.erb
<% action_url = sub.persisted? ? sub_url(sub) : subs_url %>
<% http_method = sub.persisted? ? "PATCH" : "POST" %>

<form action="<%= action_url %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="<%= http_method %>">

  <label>
    Name
    <input name="sub[name]" value="<%= sub.name %>">
  </label>
  <br>

  <label>
    Description
    <textarea name="sub[description]"><%= sub.description %></textarea>
  </label>

  <input type="submit" value="Submit!">
</form>

Christmas Homework/Reddit_Clone/app/views/subs/edit.html.erb
<div>
  <h1>Edit Sub</h1>
  <%= render "form", sub: @sub %>
</div>

Christmas Homework/Reddit_Clone/app/views/subs/index.html.erb
<div>
  <h1>Subs!</h1>
  <ul>
    <% @subs.each do |sub| %>
      <li><a href="<%= sub_url(sub) %>"><%= sub.name %></a><br></li>
    <% end %>
  </ul>
</div>

Christmas Homework/Reddit_Clone/app/views/subs/new.html.erb
<div>
  <h1>Create new sub!</h1>
  <%= render "form", sub: @sub %>
</div>

Christmas Homework/Reddit_Clone/app/views/subs/show.html.erb
<h1><%= @sub.name %></h1>

  <b>Description</b>
  <p><%= @sub.description %></p>

  <a href="<%= new_post_url %>">New Post</a>

  <a href="<%= edit_sub_url(@sub) if @sub.owner == current_user %>">Edit</a>